# Generated by Django 5.0.3 on 2024-03-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazin',
            new_name='Magazine',
        ),
    ]
