# Generated by Django 5.0.3 on 2024-03-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_rename_magazin_magazine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazine',
            new_name='Shop',
        ),
    ]
