# Generated by Django 5.0.3 on 2024-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0005_remove_shop_time_create_remove_shop_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
